### ISSUE TITLE
deb package download forbidden

### ISSUE THREAD

**Issue by falloutphil** [flathub/com.amazon.Workspaces#13]
On install:
flatpak --user install flathub com.amazon.Workspaces

I get this:
        ID                       Branch    Op   Remote    Download
 1. [✗] com.amazon.Workspaces    stable    i    flathub   1.0 kB / 26.2 MB

Error: While downloading https://d3nt0h4h6pmmc4.cloudfront.net/ubuntu/dists/bionic/main/binary-amd64/workspacesclient_3.1.0.813_amd64.deb: Server returned status 403: Forbidden
error: Failed to install com.amazon.Workspaces: While downloading https://d3nt0h4h6pmmc4.cloudfront.net/ubuntu/dists/bionic/main/binary-amd64/workspacesclient_3.1.0.813_amd64.deb: Server returned status 403: Forbidden

Any ideas?

**Comment by hubick** [comment]
Yeah, there seems to be automated pull requests to fix this, they just need to be merged/released. I'be been meaning to see if I can figure out how to at least build that PR locally, cuz I need to get this going again.

**Comment by bilelmoussaoui** [comment]
@hubick as you have gone through the whole process, maybe send a PR that bumps the runtime to 40 instead of 3.36 and we can make the bot auto-merge updates to avoid such failures in the future?

**Comment by hubick** [comment]
@bilelmoussaoui I've never built a flatpak. I was able to 

`[root ~]# flatpak install flathub org.gnome.Sdk//40`

and I modified the json, but it won't build:

```
[hubick com.amazon.Workspaces]$ flatpak-builder --force-clean --user --install build com.amazon.Workspaces.json
error: org.gnome.Platform/x86_64/40 not installed
Failed to init: Unable to find runtime org.gnome.Platform version 40
[hubick com.amazon.Workspaces]$ flatpak-builder --force-clean --user --install build com.amazon.Workspaces.json
error: org.gnome.Sdk/x86_64/40.0 not installed
Failed to init: Unable to find sdk org.gnome.Sdk version 40.0
```
And I have no idea how to bump versions or updated any of the releases stuff I see in the XML.
I also don't understand how bumping Gnome prevents such failures.

**Comment by bilelmoussaoui** [comment]
> @bilelmoussaoui I've never built a flatpak. I was able to

You also need the Platform bits to run it, `flatpak install flathub org.gnome.Platform//40`.  This should let you build it locally at least. The update to a newer runtime won't prevent such failures yes, but as the runtime is End-Of-Life, we can't use it anymore to build new version that's why all the bots's merge requests are failing and can't be automatically merged
