### ISSUE TITLE
Version 4.0.1.1302 - Unknown Error Occured

### ISSUE THREAD

**Issue by ssoto2** [flathub/com.amazon.Workspaces#20]
Running Pop OS 21.04 AWS Workspace starts but provides an error (Unknown Error Occurred) preventing from logging into a workspace. Uninstalled and removed the personal directory and still did not resolve the issue. Testing the official deb version and that works fine.

**Comment by bbhtt** [comment]
> @bbhtt I have not tested recently. I had to switch the DEB version back in March

Would be great if you can test and report back. Also if you see any errors in the terminal please share that as well. The original maintainer of this package isn't active anymore and I don't have an AWS account to test with.

Thanks!

**Comment by ssoto2** [comment]
@bbhtt I just reinstalled the flathub version of workspaces 4.2.x 
![Selection_226](https://user-images.githubusercontent.com/5123879/187738915-c7b0631f-e70b-4093-af3f-9231ee19f1b7.jpg)

This newer version of AWS workspaces is now working.

**Comment by bbhtt** [comment]
> This newer version of AWS workspaces is now working.

Great thanks. Feel free to close this.
