### ISSUE TITLE
Update GNOME runtime

### ISSUE THREAD

**Issue by k4n30** [flathub/com.amazon.Workspaces#21]
Info: org.gnome.Platform//40 is end-of-life, with reason:
   The GNOME 40 runtime is no longer supported as of March 21, 2022. Please ask your application developer to migrate to a supported platform.
Applications using this runtime:
   com.amazon.Workspaces

**Comment by jianpan** [comment]
Can this be fixed by updating this line?

https://github.com/flathub/com.amazon.Workspaces/blob/master/com.amazon.Workspaces.json#L4
