### ISSUE TITLE
Higher quality Flathub image

### ISSUE THREAD

**Issue by Eonfge** [flathub/com.amazon.Workspaces#25]
It has occurred to me that the Flathub image is only 64x which is not great. It makes the entire application look quite blurry, while there is an .svg in the package.

The reason this happens, is because there is only a scalable svg image in the package, and Flathub converts those for use on the website. 

## Fix

What you could do, is package a x64, x128 and x256 image yourself.  The easiest way is with a one-liner like this:

`"for size in 64 128 256 512; do rsvg-convert -u -w $size -h $size -f png -o $size.png $FLATPAK_DEST/share/icons/hicolor/scalable/apps/com.amazon.Workspaces.svg; install -Dm644 $size.png $FLATPAK_DEST/share/icons/hicolor/${size}x${size}/apps/com.amazon.Workspaces.png; done",`

https://github.com/flathub/network.loki.Session/blob/830469b5b0329120ae7d6b1234bb6c93be865774/network.loki.Session.json#L36

## Details

For reference, here is a high quality PNG from Amazon themselves;
https://images-na.ssl-images-amazon.com/images/I/51mwZtHQsvL.png

**Comment by bbhtt** [comment]
> For reference, here is a high quality PNG

The SVG icon provided in the .deb is also 512x512, if needed we can convert that.

>  It makes the entire application look quite blurry

Where? On the Flathub website?

> It has occurred to me that the Flathub image is only 64x 

Probably because it is taking the icon from a remote location and using the 64px one

https://github.com/flathub/com.amazon.Workspaces/blob/5289edfbe29a2243fc1443069f176a8f08d50d61/com.amazon.Workspaces.metainfo.xml#L23

I think that's redundant.

Even if you supply an icon with larger dimensions I think the Flathub website can only display at most 128px.

**Comment by Eonfge** [comment]
> > It makes the entire application look quite blurry
> 
> Where? On the Flathub website?

Ow, yes. I was perhaps a bit vague but I was talking about this page;
https://flathub.org/apps/details/com.amazon.Workspaces

> Even if you supply an icon with larger dimensions I think the Flathub website can only display at most 128px.

Sadly yes. For now there is no support for larger icons, but it might improve with beta.flathub.org

Hope this cleans it up a bit

**Comment by bbhtt** [comment]
Hello, I switched it to using a local 512px svg (to avoid conversions) icon from the .deb and removed the remote icons. The Flathub website should use a better quality icon now once the build gets published in about 4-5 hours. Please let me know if you're satisfied with it, then we can close this.

Thanks!

**Comment by Eonfge** [comment]
It looks great. Thanks for putting in the extra effort
