### ISSUE TITLE
Amazon Workspaces won’t launch

### ISSUE THREAD

**Issue by Kusho50** [flathub/com.amazon.Workspaces#70]
Been using Amazon Workspaces for about 3 weeks. I need it to do my work. A few days ago it no longer launches when I click the icon. Downloading it in software, but when I try to launch it now nothing happens. I think it updated and after the update it won’t launch.

So now to work i am forced to use Windows. Don’t want to use Windows anymore, so hoping to get this fixed.
Running Fedora 40 Workstation
Also, I have tried Unisntalling, and Reinstalling. Also completely deleted the directory.
Also have tried on 3 separate computers, all with Fedora 40, and it won’t launch on any of them.

Used Warehouse and roled back the last update workspacesclient_2024.1.4807
Afterwords the app will launch and work again.

**Comment by bbhtt** [comment]
Thank you. Looks like the last update started shipping the non-PCOIP version of the client along with the legacy version and changed the file structure of the `.deb`.

So the apply_extra stopped working. I'm trying to fix the script. If it does not work out, I'll revert the last update.

**Comment by Kusho50** [comment]
The update is out, and it works again.  Turned updates back on, and all good.
